### ISSUE TITLE
Missing LICENSE and copyright info

### ISSUE THREAD

**Issue by dutchchasman** [hackvertor/MentalJS#1]
Hi Hackvector,

Nice implementation! I have another open source project (https://github.com/forcedotcom/aura) I would really like to leverage MentalJS in but currently the source code does not have a LICENSE or copyright info specified and I wanted to see if you could add this. I was hoping for something compatible with ours (http://www.apache.org/licenses/LICENSE-2.0):

https://github.com/forcedotcom/aura/blob/master/LICENSE

Thank you,
Doug

**Comment by hackvertor** [comment]
Hi Doug

Yes no problem I'll add the apache license.

Cheers
Gareth

**Comment by hackvertor** [comment]
Okay sorry for the delay I've been busy but I've added the apache license now. Cheers.
